Display recipe neatly on a custom page
sonambenakatti/sps-team35 pull request #2
Opened 2021-06-30 19:58 UTC by MichaelQuinonesCE

Add six different recipes with links to each website (JS)
Add recipe layout (html)

Assigment given: Michael: Fake the data (JS side?), display recipe neatly on a custom page

2021-06-30 22:21 UTC, sonambenakatti approved these changes
Nice!! This is a great start before we get the database running.

2021-07-01 04:00 UTC, GROD8962 approved these changes
I concur; looks good as a prototype.

2021-07-01 17:09 UTC, anniefu requested changes
Hey Michael, I added some structuring to our repo similar to the examples throughout SPS so far, just so we all put files in the same place. Could you move these files to `src/main/webapp`?

Blocking on this change only.

2021-07-01 17:09 UTC, anniefu commented on FetchRecipe.js
> +  const recipes =
Great start!

I think the next step (for a new PR) is to generalize this formatting into a function that takes a recipe object as an input:

```
{
“id”: 0 
“link”: “some link”,
“title”: “some title”,
“like”: 5,
“category”: “some category”
}
```

And returns an HTML block that's formatted how you would like to see a recipe in the webpage. You could imagine the category's page might use it like this (pseudocode):
```
getRecipesByCategory() {
     var recipes = fetch('category-servlet');
     var recipeList = []
     for recipe in recipes {
         var formatted = formatRecipeToHTML(recipe);
         recipeList.add(formatted);
}
document.getElementById('category-page-recipe-list').innerText = recipeLIst;
```

Similarly the frontpage might call the function too with different recipes. With a convenient formatting function, we can make sure that recipes look the same no matter where they are applied. Your function could also tag the HTML block with a CSS class so you can add styling through that too.

2021-07-01 19:06 UTC, anniefu approved these changes

2021-07-01 20:56 UTC, merged